# Настройки только для отдельных экземпляров разработки и тестирования.
# Параметры запуска проверены на установленном Eclipse 4.30.
org.eclipse.urischeme/skipAutoRegistration=true
org.eclipse.ui.workbench/PLUGINS_NOT_ACTIVATED_ON_STARTUP=org.eclipse.oomph.ui;org.eclipse.oomph.setup.ui;org.eclipse.equinox.p2.ui.sdk.scheduler
